### ISSUE TITLE
Race issue leading to dialog not dismissed

### ISSUE THREAD

**Issue by bubbleguuum** [tasomaniac/DelayedProgress#1]
I found a race timing dependent issue where the dialog is not dismissed in some cases, when the dialog it dismissed shortly after it has been shown.
- ContentLoadingProgressDialog.dismiss() is called
- it fires mDelayedHide
- onAttachedToWindow() is called before mDelayedHide executes, and remove the callback
- as a consequence, the callback is not called and the dialog not dismissed

Although I could reprod it easily, it might be difficult to reproduce on a particular phone / Android version as it is really timing dependent.
Raising minShowTime to 1000 or higher seems to fix it.
It can also possibly fixed by modifying onAttachedToWindow() to not remove the callback if the dislog is in the process of being dismissed (not sure this is the correct fix though)

**Comment by tasomaniac** [comment]
Can you reproduce it everytime? What does happen in the case you wrote?
Does it flash?

**Comment by bubbleguuum** [comment]
It doesn't flash: the dialog is simply not dismissed because ProgressDialog.dismiss() is not called.

As I mentionned in the OP, it happens when onAttachedToWindow() is called before mDelayedHide runs.

**Comment by arthurprs** [comment]
Confirmed. Sometimes my dialogs are not dismissed. Do we have a workaround besides increasing the minShowTime?
