### ISSUE TITLE
Build error for 0.3

### ISSUE THREAD

**Issue by veiz** [tasomaniac/DelayedProgress#6]
Refer to https://github.com/jitpack/jitpack.io/issues/395

**Comment by jitpack-io** [comment]
Hi @veiz 

The issues is that it tries to upload to sonatype.org during the build. 
Would be easy to make it work if you used gradle properties like here: https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L40
That way it would work locally and on JitPack.

Cheers

**Comment by tasomaniac** [comment]
@jitpack-io are you sure? I am using a customized version of that code from @chrisbanes

I configured the task `uploadArchives` to upload archives to sonatype. I want my library to be hosted on sonatype. 

So, I feel like this is completely @jitpack-io 's responsibility. Jitpack is trying to build and serve my library but you fail. What can I do?

**Comment by tasomaniac** [comment]
@veiz the library is already available through mavenCentral and jcenter. Why are you trying to get it from jitpack?

**Comment by jitpack-io** [comment]
@tasomaniac Ah, I see, you're right. The customized version uses properties for username/password and only the urls are hardcoded:
https://github.com/tasomaniac/DelayedProgress/blob/master/gradle/gradle-mvn-push.gradle#L42

A tiny change would be to use properties for urls as well:
https://github.com/chrisbanes/gradle-mvn-push/blob/master/gradle-mvn-push.gradle#L24-L32
Happy to submit a PR if you're interested.

**Comment by tasomaniac** [comment]
I will of course accept that PR if you send it. 

But the problem here is with @jitpack-io I think. Are you seriously gonna send PRs to every project on github that have hardcoded reference to sonatype. You should be able to grab the artefact automatically.

**Comment by jitpack-io** [comment]
@tasomaniac That's a fair point. Grabbing the artifact automatically would be best but it's not always obvious what the artefact is and what are it's dependencies. Will look into it though

**Comment by jitpack-io** [comment]
Good news guys, it's building fine now. Many thanks to @tasomaniac for the suggestion!
https://jitpack.io/com/github/tasomaniac/DelayedProgress/0.3/build.log

**Comment by tasomaniac** [comment]
I don't understand how did you solve it :) You are still using `uploadArchives` task. But cool.
